version: "3"
services:
  mysqldb:
    container_name: achatdb3
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=achatdb
    volumes:
      - db:/var/lib/mysql

  app-timesheet:
    depends_on:
      - mysqldb
    image: mariemghadhab/achat:1.0.0
    container_name: achat3
    restart: on-failure
    ports:
      - 8090:8089
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url": "jdbc:mysql://mysqldb:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
           "spring.datasource.username": "root",
           "spring.datasource.password": null,
           "spring.jpa.show-sql": true,
           "spring.jpa.hibernate.ddl-auto": "update",
           "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
        }'
    stdin_open: true
    tty: true



volumes:
  db: